//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public Folder()
        {
            this.Note = new HashSet<Note>();
        }
    
        public int FolderID { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public System.DateTime LastModified { get; set; }
        public int Person_ID { get; set; }
    
        public virtual ICollection<Note> Note { get; set; }
        public virtual Person Person { get; set; }
    }
}
