//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<bool> Starred { get; set; }
        public Nullable<bool> Completed { get; set; }
        public int Folder_ID { get; set; }
        public int Person_ID { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual Person Person { get; set; }
    }
}
