//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<bool> Starred { get; set; }
        public Nullable<bool> Completed { get; set; }
        public int Folder_ID { get; set; }
        public int Person_ID { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual Person Person { get; set; }
    }
}
