//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Folder = new HashSet<Folder>();
            this.Note = new HashSet<Note>();
        }
    
        public int PersonID { get; set; }
        public string UserName { get; set; }
        public string PersonIDEncrypted { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public string PersonalPhrase { get; set; }
        public string PhraseColor { get; set; }
        public byte[] AvatarImage { get; set; }
        public string AvatarMIMEType { get; set; }
    
        public virtual ICollection<Folder> Folder { get; set; }
        public virtual ICollection<Note> Note { get; set; }
    }
}
